apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    type: local
  name: robacena-pvc3
spec:
  storageClassName: robacena
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    