apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
  labels:
    app: nginx
spec:
  ports:
  - port: 80 # port do container
    name: http
  clusterIP: None # garante que o service nao tera um ip virtual
  selector:
    app: nginx