apiVersion: v1
kind: Pod
metadata:
  name: nginx-with-secret
spec:
  containers:
  - name: nginx
    image: nginx:latest
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: first-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: first-secret
          key: password